[package]
name = "my_first_module"
version = "1.0.0"
authors = []

[addresses]
MyModule = "0x79c60fba4d540bb5e496d0002f93be3e5ec2a61c3ed86aad9cd1355242ecd720"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
